version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/data:/var/lib/grafana 
    ports:
      - 5000:5000
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms
      - GF_SERVER_HTTP_PORT=5000
    links:
      - prometheus

  memory_monitoring:
    build: 
       context: ./utils/
       args:
          BASE_IMAGE : ge/intel/sles_dpcpp_compiler_host_level_zero
    image: memory_monitoring_image     
    ports:
       - 8082:8082 
    volumes:
      - /sys/kernel/debug/:/sys/kernel/debug  
  
  suspend_resume_testing:
    build: 
       context: ./
       args:
          BASE_IMAGE : ge/intel/sles_dpcpp_compiler_host_level_zero
    image: suspend_resume_image     
  
